# Generated by Django 3.2 on 2021-05-29 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('facebookid', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('phonenumber', models.IntegerField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
